[env:xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
lib_deps =
    kosme/arduinoFFT@^2.0.2
    Seeed-Studio/Seeed_Arduino_SSCMA@^1.0.0
    bblanchon/ArduinoJson@^7.0.0
